development:
  access_key_id: 'SET_THIS_AS_ENV_VARIABLE'
  secret_access_key: 'SET_THIS_AS_ENV_VARIABLE'
  bucket: 'mkmdevelopment'
  url: ':s3_alias_url'
  s3_host_alias: 's3-eu-west-1.amazonaws.com/mkmdevelopment'

production:
  access_key_id: 'SET_THIS_AS_ENV_VARIABLE'
  secret_access_key: 'SET_THIS_AS_ENV_VARIABLE'
  bucket: "mkmproduction"
  s3_host_alias: 's3-eu-west-1.amazonaws.com/mkmproduction' 
